# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for spacehack — standalone macOS .app / Windows onedir.

Usage:
    pyinstaller spacehack.spec          # one-shot build
    pyinstaller --clean spacehack.spec  # fresh build (pick up data changes)
"""

import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Hidden imports — tcod uses cffi + numpy, both of which can be missed by
# PyInstaller's auto-detection.  collect_submodules grabs every spacehack
# submodule so dynamic/delayed imports don't get missed.
# ---------------------------------------------------------------------------
from PyInstaller.utils.hooks import collect_submodules

_hidden = [
    'cffi',
    'numpy',
    'tcod',
] + collect_submodules('spacehack')

# ---------------------------------------------------------------------------
# Data files: bundle the entire data/ tree so tilesheets, fonts, and
# .layout files are available at runtime via sys._MEIPASS/spacehack/data/.
# ---------------------------------------------------------------------------
_src_data = Path('src/spacehack/data')
_datas: list[tuple[str, str]] = []

if _src_data.is_dir():
    for _p in _src_data.rglob('*'):
        if _p.is_dir():
            continue
        # Compute the destination directory: spacehack/data/<relative_parent>
        _rel = _p.relative_to(_src_data)
        _dst = str(Path('spacehack') / 'data' / _rel).replace('\\', '/')
        _datas.append((str(_p), str(Path(_dst).parent)))

# ---------------------------------------------------------------------------
# Entry-point script: a tiny launcher that imports and runs the game.
# We don't use __main__.py directly because PyInstaller runs it in a weird
# namespace.  This standalone launcher avoids import-path footguns.
# ---------------------------------------------------------------------------
_LAUNCHER = """\
import sys
from spacehack.__main__ import main
sys.exit(main())
"""

_launcher_path = Path('_spacehack_launcher.py')
_launcher_path.write_text(_LAUNCHER, encoding='utf-8')

# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------
a = Analysis(
    [str(_launcher_path)],
    pathex=['src'],
    binaries=[],
    datas=_datas,
    hiddenimports=_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data)

# ---------------------------------------------------------------------------
# onedir executable — the bootloader stub carries only the launcher; every
# compiled module, C-extension, archive and data file is collected raw by
# COLLECT below.  exclude_binaries=True keeps binaries out of the stub so
# each .dylib/.pyd sits unpacked and visible to the OS — required for clean
# codesigning/notarization on macOS and far friendlier to Windows
# SmartScreen / Defender heuristics (a packed onefile exe reads as a
# generic binary blob; a folder of ordinary files does not).
# ---------------------------------------------------------------------------
exe = EXE(
    pyz,
    a.scripts,
    exclude_binaries=True,
    name='spacehack',
    icon='packaging/spacehack.ico',  # used on Windows
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

# ---------------------------------------------------------------------------
# COLLECT lays the executable out beside its raw binaries, zipfiles and
# data: dist/spacehack/ on Windows, and Contents/Frameworks/ inside the
# .app on macOS — a transparent layout the OS can read without parsing the
# bootloader stub.  upx=False avoids UPX-compressed Mach-O/PE blobs, which
# Apple's code-signature parser rejects and Windows AV heuristics flag.
# ---------------------------------------------------------------------------
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='spacehack',
)

# Icons: the amber '@' + scanner ring mark (packaging/) is generated by
# tools/make_icon.py from the bundled DejaVu Sans Mono in the game's own
# pygame_ui.Palette colours.  EXE's icon= is used on Windows; BUNDLE's on
# macOS (icon-windowed.icns lands in Contents/Resources/).
# ---------------------------------------------------------------------------
# macOS .app bundle (only built on macOS): wraps the COLLECT folder into a
# standard spacehack.app/Contents/{MacOS,Frameworks} layout so every tcod /
# numpy dylib is exposed transparently to the operating system.
#
# macOS requires every nested binary to carry at least an ad-hoc signature
# (mandatory on Apple Silicon); unsigned dylibs make the app open as
# "damaged".  PyInstaller ad-hoc signs by default, but if macOS still
# rejects the bundle, force a local deep signature (or run `make app`):
#
#     codesign --force --deep --sign - dist/spacehack.app
#     codesign --verify --verbose dist/spacehack.app
#
# Do NOT use codesign_identity='-' here: PyInstaller then also passes
# --options=runtime (hardened runtime), which makes ad-hoc-signed dylibs
# fail library validation at launch.
# ---------------------------------------------------------------------------
if sys.platform == 'darwin':
    app = BUNDLE(
        coll,
        name='spacehack.app',
        icon='packaging/spacehack.icns',
        bundle_identifier='com.spacehack.game',
        info_plist={
            'NSHighResolutionCapable': 'True',
            'CFBundleShortVersionString': '0.0.1',
            'CFBundleName': 'spacehack',
        },
    )

# Clean up the temp launcher
_launcher_path.unlink(missing_ok=True)
