"""Tests for the Pygame-independent layout editor model."""

from __future__ import annotations

from pathlib import Path

import pytest

from src.spacehack import layout_format
from tools.layout_editor.format import (
    allowed_asset_path,
    document_to_text,
    save_document,
)
from tools.layout_editor.model import (
    AssetMode,
    EditorGrid,
    load_document,
    new_document,
)
from tools.layout_editor.validation import validate_document


_DATA = Path(__file__).resolve().parent.parent / "src" / "spacehack" / "data"


def test_existing_ship_document_round_trips_through_canonical_text():
    document = load_document(_DATA / "layouts" / "scout_a.layout")
    reparsed = layout_format.parse_layout(document_to_text(document).splitlines(), "scout_a")

    assert document.mode is AssetMode.SHIP
    assert reparsed.map_lines == document.grid.lines()
    assert reparsed.tile_map["#"] is layout_format.tile_for_name("DUNGEON_WALL")
    assert reparsed.enemy_spawn_specs["R"] == ("pirate_rifleman", 1.0, 2, 4)
    assert reparsed.loot_zones["4"] == "cargo_bay"


def test_existing_landmark_document_round_trips_and_validates():
    document = load_document(_DATA / "landmarks" / "mars_signal_door.layout")

    assert document.mode is AssetMode.LANDMARK
    assert validate_document(document) == ()
    assert layout_format.parse_layout(
        document_to_text(document).splitlines(), "mars_signal_door",
    ).map_lines == document.grid.lines()


def test_grid_resize_preserves_top_left_cells_and_fills_new_area():
    grid = EditorGrid.from_lines(["abc", "def"])
    grid.resize(4, 3, ".")

    assert grid.lines() == ("abc.", "def.", "....")


def test_new_ship_document_is_valid_and_can_be_serialized():
    document = new_document(AssetMode.SHIP)

    assert validate_document(document) == ()
    assert "MAP\n###\n#P#\n#>#\nENDMAP" in document_to_text(document)


def test_validation_reports_unknown_glyph_and_missing_spawn():
    document = new_document(AssetMode.SHIP)
    document.grid.set_char(1, 1, "?")
    document.grid.set_char(0, 1, ".")

    messages = {issue.message for issue in validate_document(document)}
    assert "Unknown glyph '?'" in messages
    assert "Ship layouts require exactly one P spawn marker" in messages


def test_save_document_writes_canonical_text_and_clears_dirty_state(tmp_path):
    root = tmp_path / "repo"
    layouts = root / "src" / "spacehack" / "data" / "layouts"
    layouts.mkdir(parents=True)
    document = new_document(AssetMode.SHIP)
    document.dirty = True

    destination = save_document(document, layouts / "example.layout", root=root)

    assert destination == (layouts / "example.layout").resolve()
    assert destination.read_text(encoding="utf-8").startswith(
        "# example — generated by spacehack layout editor\n",
    )
    assert document.path == destination
    assert not document.dirty


def test_save_path_is_limited_to_direct_repository_asset_directory(tmp_path):
    root = tmp_path / "repo"
    layouts = root / "src" / "spacehack" / "data" / "layouts"
    layouts.mkdir(parents=True)
    valid = layouts / "example.layout"

    assert allowed_asset_path(valid, AssetMode.SHIP, root) == valid.resolve()
    with pytest.raises(ValueError, match="must be saved directly"):
        allowed_asset_path(root / "example.layout", AssetMode.SHIP, root)
    with pytest.raises(ValueError, match="must be saved directly"):
        allowed_asset_path(
            root / "src" / "spacehack" / "data" / "landmarks" / "example.layout",
            AssetMode.SHIP,
            root,
        )
