"""Canonical serialization and safe path handling for layout documents."""

from __future__ import annotations

import os
from pathlib import Path
import tempfile

from .model import AssetMode, EditorDocument


_PROJECT_ROOT = Path(__file__).resolve().parents[2]


def asset_directories(root: Path | None = None) -> dict[AssetMode, Path]:
    """Return the two repository directories where authored assets belong."""
    root = root or _PROJECT_ROOT
    data = root / "src" / "spacehack" / "data"
    return {
        AssetMode.SHIP: data / "layouts",
        AssetMode.LANDMARK: data / "landmarks",
        AssetMode.CITY: data / "landmarks",
    }


def allowed_asset_path(
    path: str | Path,
    mode: AssetMode,
    root: Path | None = None,
) -> Path:
    """Validate and normalize a destination in the selected asset directory."""
    path = Path(path).expanduser().resolve()
    directory = asset_directories(root)[mode].resolve()
    if path.parent != directory or path.suffix != ".layout":
        raise ValueError(
            f"{mode.value} assets must be saved directly in {directory}"
        )
    return path


def _format_chance(chance: float) -> str:
    """Format a directive probability without unnecessary zeroes."""
    return f"{chance:g}"


def _format_enemy(directive) -> str:
    """Format one enemy directive in the shared source syntax."""
    squad = f"#{directive.squad_min}-{directive.squad_max}"
    return (
        f"ENEMY: {directive.glyph} = {directive.enemy_id}"
        f"@{_format_chance(directive.chance)}{squad}"
    )


def _format_colour(directive) -> str:
    """Format one foreground-only or foreground/background color."""
    fg = f"({directive.fg[0]}, {directive.fg[1]}, {directive.fg[2]})"
    if directive.bg is None:
        return f"COLOUR: {directive.glyph} = {fg}"
    bg = f"({directive.bg[0]}, {directive.bg[1]}, {directive.bg[2]})"
    return f"COLOUR: {directive.glyph} = {fg} / {bg}"


def document_to_text(document: EditorDocument) -> str:
    """Serialize a document to deterministic canonical layout text."""
    name = document.path.stem if document.path else "new_layout"
    lines = [
        f"# {name} — generated by spacehack layout editor",
        "",
        "MAP",
        *document.grid.lines(),
        "ENDMAP",
        "",
        "# Tile mappings",
    ]
    lines.extend(
        f"TILE: {glyph} = {document.tile_directives[glyph].tile_name}"
        for glyph in sorted(document.tile_directives)
    )
    if document.enemy_directives:
        lines.extend(("", "# Enemy spawn markers"))
        lines.extend(
            _format_enemy(document.enemy_directives[glyph])
            for glyph in sorted(document.enemy_directives)
        )
    if document.loot_directives:
        lines.extend(("", "# Loot room markers"))
        lines.extend(
            f"LOOT: {glyph} = {document.loot_directives[glyph].room_type}"
            for glyph in sorted(document.loot_directives)
        )
    if document.colour_directives:
        lines.extend(("", "# Color overrides"))
        lines.extend(
            _format_colour(document.colour_directives[glyph])
            for glyph in sorted(document.colour_directives)
        )
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, text: str) -> None:
    """Replace a destination only after its complete text is written."""
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(text)
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def save_document(
    document: EditorDocument,
    path: str | Path | None = None,
    *,
    root: Path | None = None,
) -> Path:
    """Write a document to an allowed repository asset path."""
    destination = Path(path) if path is not None else document.path
    if destination is None:
        raise ValueError("a destination path is required")
    destination = allowed_asset_path(destination, document.mode, root)
    previous_path = document.path
    document.path = destination
    try:
        _atomic_write(destination, document_to_text(document))
    except OSError:
        document.path = previous_path
        raise
    document.dirty = False
    return destination
