"""Interactive game guide — the ``?`` key.

Press ``?`` at any time to open a browsable menu of topic sections
explaining every system in spacehack. The guide pauses game state
while open; dismiss with ESC from the topic list or ESC from any
section page.

Covers combat formulas, trade mechanics, mission flow, ship systems,
navigation, character skills, factions, and keybindings.
"""

from __future__ import annotations

from dataclasses import dataclass

from .game_context import GameContext

# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class GuideSection:
    """One topic in the game guide.

    ``title`` is shown in the topic list and as the page heading.
    ``body`` is plain text, word-wrapped at render time via
    :func:`spacehack.ui.wrap_text`. Keep sections self-contained;
    cross-references use plain English ("see Trading & Economy").
    """
    title: str
    body: str

# ---------------------------------------------------------------------------
# Section content
# ---------------------------------------------------------------------------

_GUIDE_GAME_OVERVIEW = GuideSection(
    title="Game Overview",
    body=(
        "The year is 2200. Humankind has spread across more than a dozen "
        "star systems, linked by jump gates of unknown origin. You are a "
        "freelance pilot making a living on the frontier."
        "\n\n"
        "How it works:"
        "\n"
        "- Start in a city on Earth"
        "\n"
        "- Buy a ship at the spaceport"
        "\n"
        "- Launch into the Sol system"
        "\n"
        "- Travel to other systems via jump gates"
        "\n"
        "- Take missions (up to 5 at once) and trade goods to earn credits"
        "\n"
        "- Upgrade your ship and repeat"
        "\n\n"
        "Death is permanent: when your ship is destroyed in combat, a"
        "full-screen death frame appears (no HUD, no console log) and"
        "any key returns you to the main menu. The run is not saved -"
        "you start a fresh run from Earth."
        "\n\n"
        "Game time advances as you fly through space - every 10 or so"
        "moves (depending on your ship's speed) equals one day. Watch"
        "the date in the HUD; months rolling over trigger shop restocks"
        "and economy ticks."
        "\n\n"
        "City mode: walk around the city with h/j/k/l. Walk into entities"
        "to interact - ships at the spaceport (buy/launch), NPCs in guild"
        "halls (talk/missions), terminals (trade/repair)."
        "\n\n"
        "Space mode: fly your ship on the solar system map. Bump into"
        "planets to land, fly into jump gates to travel between systems."
    ),
)

_GUIDE_CONTROLS = GuideSection(
    title="Controls & Keybindings",
    body=(
        "Movement: arrow keys, h/j/k/l, or numpad for cardinals; "
        "y/u/b/n (or numpad 7/9/1/3) for diagonals."
        "\n\n"
        "City mode:"
        "\n"
        "- C: view character screen (level, skills, traits)"
        "\n"
"- F: view faction standings"
        "\n"
        "- Q: open quest log (view or abandon mission)"
        "\n"
        "- Walk into entities to interact: ships (buy/launch, view"
        "cargo, view loadout), NPCs (talk/missions), terminals"
        "(trade, mechanic: refuel/repair/manage loadout)"
        "\n"
        "- ESC: save and exit to the main menu (asks first)"
        "\n\n"
        "Space mode:"
        "\n"
        "- P: pick up nearby loot"
        "\n"
        "- G: auto-nav (Go To) toward a selected target"
        "\n"
        "- M: navigation map showing planets, gates, your ship"
        "\n"
        "- I: cargo hold"
        "\n"
        "- \\: full console log (scrollable history)"
        "\n"
        "- C: view character screen (level, skills, traits)"
        "\n""- T: comms panel (hail nearby ships)"
        "\n"
        "- F: faction standings viewer"
        "\n"
        "- Period (.): wait one turn (pirates move, shields regen)"
        "\n"
        "- ESC: ship menu"
        "\n"
        "- ?: this guide"
        "\n\n"
        "Combat keys:"
        "\n"
        "- Arrow keys, h/j/k/l, or numpad: move on the tactical grid"
        "\n"
        "- TAB: cycle targets"
        "\n"
        "- F: fire burst - all active weapons at current target"
        "\n"
        "- 1-9: toggle each weapon on/off ([x] = active, [ ] = inactive)"
        "\n"
        "- S: cycle shield regen rate (0-10)"
        "\n"
        "- W: wait (end your turn)"
        "\n"
        "\n\n"
        "Modal keys (trade, cargo, menus):"
        "\n"
        "- Arrow keys or j/k: navigate"
        "\n"
        "- ENTER: confirm"
        "\n"
        "- ESC: cancel or go back"
        "\n"
        "- TAB: switch between panels (buy/sell in loadout)"
        "\n"
        "- +/-: adjust quantities"
        "\n\n"
        "Developer mode (SPACEHACK_DEV=1):"
        "\n"
        "- Shift+O: choose your Act 0 faction, then skip to the Mars door-opening interaction"
        "\n"
        "- Shift+R: reveal all dungeon fog"
        "\n"
        "- Shift+D: advance the clock by 30 days"
        "\n"
        "- Shift+X: award 200 XP"
        "\n"
        "- New dev games start with two kinetic rifles and the best armor in every slot"
    ),
)

_GUIDE_DUNGEON_EXTENSIONS = GuideSection(
    title="Themed Dungeon Extensions",
    body=(
        "Some dungeon sites lead into deeper themed extensions. The Mars "
        "signal door opens onto a procedural alien-prison floor."
        "\n\n"
        "- Step onto the green > stairs marker to enter"
        "\n"
        "- Explore normally; the extension floor is persistent"
        "\n"
        "- Dormant security may power up as you travel deeper"
        "\n"
        "- Main-quest popups explain major systems waking up"
        "\n"
        "- Extracting the Floor 5 data fully powers the emergency systems; "
        "the ascent becomes a security lockdown"
        "\n"
        "- On the way back, each floor stages new encounters toward its upper "
        "stairs; the response escalates from sentry pairs to multiple heavy "
        "assault frames"
        "\n"
        "- Ascent encounters trigger once per prison run and remain completed "
        "when you backtrack or Continue"
        "\n"
        "- Use < to climb back toward the previous floor; on Floor 1 it "
        "returns to the parent Mars dungeon"
        "\n"
        "- Floors 2-3 are persistent procedural areas with low-risk "
        "quarters and a defensive layer"
        "\n"
        "- Floor 4 contains larger high-risk cells and an engineering console"
        "\n"
        "- Restore engineering power before using the deep elevator"
        "\n"
        "- Defeated enemies, collected loot, and revealed fog remain when "
        "you backtrack"
        "\n"
        "- The deeper > stairs on Floor 2 lead to the defensive Floor 3"
        "\n"
        "- The powered elevator on Floor 4 descends to the deep cell"
        "\n"
        "- Floor 5 is a hand-authored giant holding cell stamped into the "
        "procedural floor: the elevator opens onto a long bridge over a "
        "deep void, then a terminal-lined landing before the torn entrance; "
        "claw scars cross the empty chamber and only the single live terminal "
        "(T) responds"
        "\n"
        "- Extracting the terminal's data completes the opening Act 1 prison "
        "objective and powers the emergency systems; the post-prison research "
        "trail begins when you leave Mars"
        "\n"
        "- The route back is not safe: once the data is extracted, climb toward "
        "the upper stairs and fight the newly awakened security on every floor"
        "\n\n"
        "Post-prison orbit:"
        "\n"
        "- Return to the Mars surface by the Floor 1 < stairs, then launch "
        "into orbit. Once you are in orbit, the archive wakes up in your "
        "communications array. It is not translated yet, but it appears "
        "to answer something."
        "\n"
        "- Choose whether to transmit a diagnostic fragment, keep the archive "
        "sealed, or ask for a safe destination. The choice is "
        "recorded and changes the tone of later interpretations; it does not "
        "lock the final ending."
        "\n"
        "- If you keep the archive sealed, deliver it immediately to the Research "
        "Officer at Alpha Centauri's Science Port. There is no waiting period: "
        "you are carrying the complete record. If you transmit a fragment or ask "
        "for a secure destination, the remote analysis or logistics work takes "
        "time; the quest log explains that specific wait and the summons has no "
        "deadline."
        "\n"
        "- The first interpretation takes place at the Alpha Centauri Science "
        "Port. The route beyond Luyten is a hypothesis, not proof of a colony, "
        "weapon, or rescue path."
    ),
)

_GUIDE_COMBAT = GuideSection(
    title="Combat System",
    body=(
        "Combat is turn-based on the space map. Each ship has Action Points"
        "(AP), power, shields, and hull hit points."
        "\n\n"
        "Action Points:"
        "\n"
        "- AP per turn = 3 + (Piloting // 20)"
        "\n"
        "- Move: 1 AP per cell"
        "\n"
        "- Fire: AP cost varies by weapon"
        "\n"
        "- When AP reaches 0, the enemy takes their turn"
        "\n\n"
        "Hit chance:"
        "\n"
        "chance = weapon_accuracy + (Gunnery * 0.5)"
        "\n"
        "       + close_bonus (5% if within half max range)"
        "\n"
        "       - dist_penalty (10% per cell beyond max range)"
        "\n"
        "       - min_penalty (5% per cell inside min range)"
        "\n"
        "       - target_dodge_bonus"
        "\n"
        "Result clamped to 5%-95% (always a chance to hit or miss)."
        "\n\n"
        "Dodge bonus:"
        "\n"
        "- +5% per cell moved this turn (cap 30%)"
        "\n"
        "- + (Piloting * 0.5), soft-capped at 60% total"
        "\n"
        "- Moving makes you harder to hit"
        "\n\n"
        "Damage:"
        "\n"
        "raw = weapon_damage * quality_mult (50%-100%)"
        "\n"
        "     * variance (80%-120%)"
        "\n"
        "Shields absorb damage before hull. Hull at 0 = ship destroyed."
        "\n"
        "Enemies with high Piloting skill may cause glancing hits that"
        "deal half damage."
        "\n\n"
        "Weapon burst fire:"
        "\n"
        "- Toggle weapons on/off with number keys (1-9)"
        "\n"
        "- Active weapons show [x] in the HUD; inactive show [ ]"
        "\n"
        "- F fires ALL active weapons in a single burst action"
        "\n"
        "- AP cost = highest AP cost among active weapons"
        "\n"
        "- Power cost = sum of all active energy weapons' power costs"
        "\n"
        "- Ammo is consumed per missile launcher fired - and ammo is"
        "PERSISTENT: rounds spent in combat stay spent until you rebuy"
        "them at the mechanic (Buy Ammo)"
        "\n"
        "- Each launcher keeps its own magazine: two heavy missile"
        "launchers fire and deplete independently"
        "\n"
        "- Each weapon rolls hit/damage independently"
        "\n"
        "- Tactical choice: burst for max damage, or deselect"
        "weapons to conserve power/ammo"
        "\n\n"
        "Shield regeneration:"
        "\n"
        "- Set rate 0-10 per turn with the S key"
        "\n"
        "- Each point of regen costs power (rate - Engineering/20)"
        "\n"
        "- Higher Engineering = cheaper shield regen"
        "\n"
        "- Certain modules (Shield Recharger) give free regen that"
        "stacks on top of the player-set rate"
        "\n\n"
        "Fleeing is not currently implemented. Fight to victory or death."
        "\n"
        "base = 30% + (your Piloting - enemy Piloting) * 2"
        "\n"
        "     + hull_desperation (20% at 0 hull)"
        "\n"
        "     - close_dist_penalty (5%/cell under 5)"
        "\n"
        "     + 10% per previous failed attempt"
        "\n"
        "Result clamped 5%-95%."
        "\n\n"
        "Combat HUD layout (right-side panel):"
        "\n"
        "- Player block: shields (cyan bar), hull (green/yellow/red),"
        "AP with evade bonus, power with next-turn regen (+N); a"
        "white highlight on the left of the shield bar marks your"
        "regen rate (S cycles it 0-10)"
        "\n"
        "- Enemy block: each enemy shows name + distance, then"
        "shield bar (cyan) above hull bar with %"
        "\n"
        "- Weapons list: each weapon shows [x]/[ ] toggle, DMG,"
        "effective HIT %, and cost (POW or AMMO + AP)"
        "\n"
        "- Actions panel: keybindings for Target, Move, Fire,"
        "Shields, Wait"
        "\n"
        "Weapon types:"
        "\n"
        "- Energy (lasers): cost power, unlimited ammo"
        "\n"
        "- Missile: no power cost, long range, scarce ammo (takes cargo"
        "space). Spent rounds persist until rebought at the mechanic"
        "\n"
        "- EMP Missile: 0 hull damage but strips 20 shields per hit"
        "(ignore armor/hull entirely)"
    ),
)

_GUIDE_TRADE = GuideSection(
    title="Trading & Economy",
    body=(
        "Trade terminals appear as = symbols on the city map. Walk into"
        "one to buy and sell goods. The split-screen terminal shows the"
        "station's stock on the left and your hold on the right; TAB"
        "switches panels and ENTER buys or sells."
        "\n\n"
        "Basic strategy:"
        "\n"
        "- Buy goods on planets that produce them (low price)"
        "\n"
        "- Sell on planets that consume them (high price)"
        "\n"
        "- Each planet has its own economic profile with supply/demand"
        "\n"
        "- Prices fluctuate based on current stock levels"
        "\n\n"
        "Cargo:"
        "\n"
        "- Your ship has a cargo capacity (shown in the HUD)"
        "\n"
        "- Each good takes up a certain amount of cargo space"
        "\n"
        "- Plan your loadout based on your destination"
        "\n"
        "- Current credits and cargo space are always visible in the"
        "HUD sidebar"
        "\n\n"
        "Stock levels:"
        "\n"
        "- Stock is tracked per-planet and replenishes over time"
        "\n"
        "- You cannot sell more than the planet demands"
        "\n"
        "- You cannot buy more than the planet has in stock"
        "\n\n"
        "The mechanic terminal (% on the city map) handles refueling,"
        "repairs, loadout management, and missile-ammo purchases,"
        "not trading."
    ),
)

_GUIDE_MISSIONS = GuideSection(
    title="Missions",
    body=(
        "Talk to NPCs in guild halls (walk into them) and choose 'View "
        "available work' to see their current mission board. Each row "
        "shows the mission type, reward, and the destination solar "
        "system (unless the title already names it). You can hold "
        "up to 5 active missions - press Q to open the quest log."
        "\n\n"
        "Mission types:"
        "\n"
        "- Delivery: take cargo to a specific NPC on another planet."
        "Travel there, land, and talk to the recipient. If multiple"
        "missions are deliverable at the same NPC, the talk menu shows"
        "one 'Deliver: <title>' row per mission - arrow-key to choose."
        "\n"
        "- Bounty: accept a contract to hunt down a named enemy in a"
        "target star system. Travel there and find the target - your"
        "ship's sensors will ping when you enter the right system."
        "When within comms range, the target may hail you with a"
        "taunt. Engage and destroy them to complete the mission."
        "Higher-tier bounties may have wingmates who join the fight."
        "Only the named leader counts for completion."
        "\n\n"
        "Tiers (1-4):"
        "\n"
        "- Missions have a tier that controls cargo size, difficulty,"
        "and rewards. Higher-tier planets offer higher-tier missions."
        "\n"
        "- Delivery T1 (Local): 5-10 cargo, 50-120$, same system or up to"
        " 2 jumps"
        "\n"
        "- Delivery T2 (Regional): 10-20 cargo, 160-330$, 1-3 jumps"
        "\n"
        "- Delivery T3 (Sector): 20-40 cargo, 420-850$, 2-5 jumps"
        "\n"
        "- Delivery T4 (Frontier): 40-60 cargo, 1030-1570$, 3-7 jumps"
        "\n"
        "- Payout adds +10$ per jump from the pickup planet - a mission"
        "accepted on Mars pays for the distance to its destination"
        "\n"
        "- Bounty rewards scale with target hull strength, tier, and"
        "squad size - higher tiers pay significantly more."
        "\n\n"
        "Bounties in detail:"
        "\n"
        "- Accept from any Bounty Master NPC (South-East city district)."
        "\n"
        "- The target spawns in the target system with a custom name"
        "(e.g. 'Crimson Jack'). Procedural bounties generate random"
        "names from a pool of adjectives + first names."
        "\n"
        "- Comms warning: when you fly within warning range, the"
        "target hails you automatically with a taunt. Choosing"
        "'Attack' from comms starts combat with the full squad."
        "\n"
        "- Squad bounties: higher tiers may spawn wingmates who"
        "fight alongside the leader. Hailing any member and choosing"
        "'Attack' pulls the whole squad into combat. Only destroying"
        "the leader completes the mission - wingmates are bonus enemies."
        "\n"
        "- The quest log shows danger level (Low/Moderate/High/"
        "Extreme), target system, and squad size."
        "\n\n"
        "Static vs procedural missions:"
        "\n"
        "- Static (hand-crafted): unique, don't repeat after completion."
        "Abandoning one returns it to the giver's board."
        "\n"
        "- Procedural (generated): infinite variety, weighted so higher"
        "tiers appear less often. Abandoning a procedural mission"
        "discards it forever - a new one generates in its place."
        "\n\n"
        "Mission boards:"
        "\n"
        "- Each mission-giver NPC has a 5-slot board."
        "\n"
        "- Boards refill when the game month rolls over (every 30 days)."
        "\n"
        "- Static missions fill empty slots first, then procedural."
        "\n\n"
        "Deadlines & bonuses:"
        "\n"
        "- Most missions have a deadline in days. Check the quest log (Q)"
        "for 'Due: YYYYMMDD (N days)'."
        "\n"
        "- Early bonus: deliver in less than half the deadline for +25-30%"
        "extra credits."
        "\n"
        "- On time: full pay."
        "\n"
        "- Late (past deadline): half credits, no XP (bounties can still"
        "be completed)."
        "\n"
        "- The quest log shows 'Due: YYYYMMDD (0 days)' on the deadline"
        "day (still on time). Only strictly past the deadline shows"
        "'EXPIRED' in red."
        "\n\n"
        "Quest log (Q):"
        "\n"
        "- List of all active missions with arrow-key navigation."
        "\n"
        "- Detail pane shows type, destination, cargo or target, reward,"
        "deadline, and (for bounties) danger level and squad size."
        "\n"
        "- Every mission shows the solar system you need to fly to: "
        "deliveries and smuggling runs say 'Deliver to <planet> in "
        "<system>', bounties and intercepts name the target's system, "
        "and salvage missions show the patrol's system."
        "\n"
        "- Out-and-back missions (intercept, salvage) show a 'Return to:'"
        "line with the planet and NPC where you hand in the secured cargo"
        "\n"
        "- Press A to abandon (confirm with ENTER)."
        "\n\n"
        "Cargo:"
        "\n"
        "- Delivery missions reserve cargo space on accept. Mission cargo"
        "persists through ship upgrades (if the new ship has room)."
        "\n"
        "- Abandoning or completing a mission releases its cargo."
        "\n"
        "- Bounty missions have no cargo - just bring your guns."
    ),
)

_GUIDE_SHIPS = GuideSection(
    title="Ships & Equipment",
    body=(
        "Buy a ship by walking into the ship entity at the spaceport."
        "Each ship has: speed (moves per day), hull strength, fuel capacity,"
        "cargo capacity, weapon slots, module slots, base shields,"
        "and power gen."
        "\n\n"
        "Ship speed affects travel time:"
        "\n"
        "- Scout (14): fastest - 14 moves per day"
        "\n"
        "- Skiff (10): your free starting ship - baseline pace. Its "
        "name is rolled fresh each run (e.g. Corvid, Old Bess, Lady "
        "Luck), so your ship feels like yours from day one."
        "\n"
        "- Hauler (7) / Freighter (6): slow but huge cargo"
        "\n"
        "- Cruiser (9) / Frigate (8): combat-focused, moderate speed"
        "\n"
        "- Speed determines how many space moves equal one game day"
        "\n"
        "- Engine modules (reactors) boost your ship's speed -"
        "a Mk.4 Reactor adds +4 moves/day to any hull"
        "\n\n"
        "Starting loadout:"
        "\n"
        "- Each ship comes with specific weapons and modules"
        "pre-installed (check the LOADOUT tab after buying)"
        "\n"
        "- Trade in your current ship for 50% of its purchase"
        "price when upgrading"
        "\n"
        "- Ships are distributed across planets by tier: basic"
        "models on Earth/Mars, advanced ships in deep space"
        "\n\n"
        "Your ship in the hangar:"
        "\n"
        "- Bump your ship to open one tabbed screen: SHIP,"
        "CARGO, and LOADOUT"
        "\n"
        "- SHIP shows your ship at a glance (fuel, hull, speed,"
        "shields, power, cargo) and the Launch action"
        "\n"
        "- CARGO lists your hold; ENTER jettisons the"
        "selected good (with a quantity prompt)"
        "\n"
        "- LOADOUT shows every slot under WEAPON SLOTS and MODULE"
        "SLOTS; installed gear fills its slot, empty slots read"
        "[empty]"
        "\n"
        "- TAB switches tabs; ESC walks away"
        "\n"
        "- Stats reflect module bonuses: shields, power gen,"
        "and cargo capacity all include installed modules"
        "\n\n"
        "Tech levels:"
        "\n"
        "- Each planet has a tech level (1-4) that determines"
        "what equipment the mechanic stocks"
        "\n"
        "- TL1 planets (Earth, Mercury): basic weapons and"
        "modules"
        "\n"
        "- TL2 planets (Mars, Venus, Tau Ceti, etc.): mid-tier"
        "weapons and modules"
        "\n"
        "- TL3 planets (Epsilon Eridani, Barnard's b): advanced"
        "gear"
        "\n"
        "- TL4 planets (Sirius Station, Blockade): cutting-edge"
        "military hardware"
        "\n"
        "- Planets with fixed inventories (Earth, Mars) always"
        "stock the same items"
        "\n\n"
        "Managing your loadout at the mechanic:"
        "\n"
        "- Walk into the % terminal on the city map, then"
        "choose 'Manage Loadout'"
        "\n"
        "- Left panel: buy new weapons and modules"
        "(sorted by price)"
        "\n"
        "- Right panel: your installed weapon and module"
        "slots, with sell prices"
        "\n"
        "- TAB: switch between buy and sell panels"
        "\n"
        "- ENTER: buy the selected item (left) or sell the"
        "installed part (right, 50% refund)"
        "\n"
        "- Cannot buy beyond your ship's slot limits"
        "\n\n"
        "Weapons:"
        "\n"
        "- Light Laser (TL1): 4 dmg, 80% acc, 1 AP, 1 power"
        "\n"
        "- Medium Laser (TL1): 6 dmg, 72% acc, 1 AP, 1 power"
        "\n"
        "- Heavy Laser (TL2): 12 dmg, 68% acc, 1 AP, 2 power"
        "\n"
        "- Plasma Cannon (TL3): 24 dmg, 70% acc, 2 AP, 4 power"
        "\n"
        "- Light Missile (TL1): 14 dmg, 72% acc, 2 AP, 4 ammo, range 2-9,"
        "8$/rd to rebuy"
        "\n"
        "- Heavy Missile (TL3): 32 dmg, 72% acc, 2 AP, 3 ammo, range 3-13,"
        "20$/rd to rebuy"
        "\n"
        "- EMP Missile (TL4): 0 dmg (strips 20 shields per hit), 75% acc,"
        "2 AP, 2 ammo, range 2-10, 25$/rd to rebuy"
        "\n\n"
        "Modules (Mk.1-Mk.4 progression available at mechanic):"
        "\n"
        "- Reactors (engine slot): Compact Reactor Mk.1 (+3 power,"
        "TL1), Reactor Mk.2 (+5, TL2), Mk.3 (+8, TL3),"
        "Mk.4 (+12, TL4)"
        "\n"
        "- Heavy Reactor (TL3): +6 power, -1 cargo"
        "\n"
        "- Shields (system slot): Mk.1 (+20, TL1), Mk.2 (+40, TL2),"
        "Mk.3 (+65, TL3), Mk.4 (+95, TL4)"
        "\n"
        "- Targeting (system slot): Computer (+10 gunnery, TL2),"
        "Array Mk.2 (+15, TL3), Mk.3 (+20, TL4), Mk.4 (+30, TL4)"
        "\n"
        "- Gyro (system slot): Stabilizer (+10 piloting, TL2),"
        "Array Mk.2 (+15, TL3), Mk.3 (+20, TL4), Mk.4 (+30, TL4)"
        "\n"
        "- Cargo (system slot): Mk.1 (+30, TL1), Mk.2 (+60, TL2),"
        "Mk.3 (+100, TL3), Mk.4 (+160, TL4)"
        "\n"
        "- Smuggler's Hold (system slot): Mk.1 (10 cargo, TL1), Mk.2 "
        "(25, TL2), Mk.3 (50, TL3), Mk.4 (75, TL4) - conceals that much "
        "contraband volume from militia cargo scans (see Bar Missions). "
        "Sold openly at the pirate-run mechanic on Wolf 359 b - the "
        "frontier stop where smugglers gear up."
        "\n"
        "- Armor (system slot): Mk.1 (+5 hull/-1 power, TL2),"
        "Mk.2 (+10/-2, TL3), Mk.3 (+15/-3, TL4), Mk.4 (+25/-4, TL4)"
        "\n"
        "- Shield Capacitor (TL2): +15 max shields (lightweight"
        "alternative to Mk.2)"
        "\n"
        "- Shield Recharger (TL3): +3 shield regen per turn"
        "(free regen, no power cost)"
        "\n\n"
        "Mechanic terminal (% on the city map):"
        "\n"
        "- One tabbed screen: REPAIRS, AMMO, and LOADOUT"
        "\n"
        "- TAB switches tabs; the AMMO tab only appears when a missile"
        "launcher is installed"
        "\n"
        "- REPAIRS: Refuel at per-unit cost; Repair restores hull"
        "(full repair costs 10% of the ship's value, less for partial"
        "damage)"
        "\n"
        "- AMMO: replenish missile magazines (8-25$ per round); ammo"
        "spent in combat stays spent until rebought. Each launcher is"
        "listed separately with its own magazine"
        "\n"
        "- LOADOUT: shows installed weapons and modules; ENTER opens"
        "the buy/sell parts market"
    ),
)

_GUIDE_NAVIGATION = GuideSection(
    title="Navigation & Jump Gates",
    body=(
        "Space mode places you on a solar system map. Each system contains"
        "planets, jump gates, stations, and other ships. The view scrolls"
        "as you move."
        "\n\n"
        "Jump gates:"
        "\n"
        "- Connect star systems - fly into one to see where it leads"
        "\n"
        "- Jumping costs fuel per jump"
        "\n"
        "- Without enough fuel the jump is blocked"
        "\n"
        "- You arrive at the matching gate in the destination system"
        "\n\n"
        "G (Go To):"
        "\n"
        "- Opens a target-selection overlay"
        "\n"
        "- Pick a planet or jump gate to auto-navigate there"
        "\n"
        "- Combat triggers automatically if enemies cross your path"
        "\n"
        "- Time advances with distance - longer trips take more days"
        "\n\n"
        "M (Map):"
        "\n"
        "- Navigation overlay showing the system layout"
        "\n"
        "- Lists planet names, jump gate connections, and distance"
        "\n\n"
        "Period (.):"
        "\n"
        "- Wait one turn - pirates move, shields regenerate"
        "\n"
        "- Useful for letting enemies come to you"
        "\n\n"
        "Planets:"
        "\n"
        "- Fly into one to approach. Land if it has a port"
        "\n"
        "- The sun, planets, stations, and jump gates are solid space objects; "
        "they stop your ship, but they are not map walls"
        "\n"
        "- Without a port you can only fly past"
        "\n"
        "- Militia checkpoints (planets with a militia building) warn you"
        "on approach: the planet menu shows a checkpoint warning before"
        "you land. Landing triggers a possible cargo scan by local militia"
        "- If a scan runs, the militia hails you first \u2014 you'll see it"
        "happen even when your cargo is clean"
    ),
)

_GUIDE_CHARACTER = GuideSection(
    title="Character & Skills",
    body=(
        "At the start you choose a species and a class. These determine"
        "your starting skills. All skills begin at base 10, then species"
        "and class bonuses are added."
        "\n\n"
        "Species:"
        "\n"
        "- Human: +2 Gunnery, +2 Engineering; ground +2 Reflexes, +2 Stamina"
        "\n"
        "- Martian: +4 Piloting; ground +4 Reflexes"
        "\n\n"
        "Classes:"
        "\n"
        "- Pirate: +12 Gunnery; ground +12 Strength; starts with 25$"
        "\n"
        "- Merchant: +12 Engineering; ground +12 Stamina; starts with 75$"
        "\n"
        "- Bounty Hunter: +4 Gunnery, +4 Piloting, +4 Engineering; "
        "ground +4 all three stats; starts with 50$"
        "\n\n"
        "Starting credits sit far below the cheapest ship (Scout, 5,000$) - "
        "earn your first upgrade from missions and trade."
        "\n\n"
        "Ship skills (affect space combat):"
        "\n"
        "- Gunnery: +0.5% hit chance per point in space combat"
        "\n"
        "- Piloting: determines AP/turn (3 + Piloting//20) and dodge"
        "(+0.5% per point, capped at 60%)"
        "\n"
        "- Engineering: reduces shield regen power cost (-1 per 20"
        "points) and increases max power pool (+1 per 5 points)"
        "\n\n"
        "Ground stats (affect foot combat in dungeons, all cap at 100):"
        "\n"
        "- Reflexes: improves ranged accuracy and dodge bonus on foot"
        "\n"
        "- Strength: increases melee damage and two-handed weapon"
        "efficiency"
        "\n"
        "- Stamina: increases HP pool and damage resistance"
        "\n\n"
        "All six skills are shown on the C screen Stats tab and the HUD."
        "Spend skill points gained from leveling up on any skill -- ship"
        "or ground -- at the same cost.  All six cap at 100."
    ),
)

_GUIDE_LEVELING = GuideSection(
    title="Leveling & Traits",
    body=(
        "Every action earns XP. Once you cross a level threshold you"
        "gain 9 skill points and your level increases. Press C to open"
        "the Character screen where you can spend points on any of the"
        "six skills (ship or ground)."
        "\n\n"
        "XP sources:"
        "\n"
        "- Completing a mission: XP scales with tier and distance"
        "\n"
        "- Destroying an enemy in combat: XP = enemy base hull * 2"
        "\n"
        "- XP gains are logged as \"+N XP\" in the message area"
        "\n\n"
        "Level curve:"
        "\n"
        "- Each level costs 50 + level * 20 XP"
        "\n"
        "- Example: level 1 to 2 costs 90 XP (one mission or a few kills)"
        "\n"
        "- Level 20 costs 450 XP, level 30 costs 650 XP"
        "\n"
        "- Max level is 30 - cumulative XP needed is about 12,860"
        "\n"
        "- Every level grants 9 skill points"
        "\n"
        "- Each point adds +1 to one skill (soft cap at 100)"
        "\n"
        "- A level 30 specialist can max out 3 of the 6 skills"
        "\n\n"
        "Character screen (C key):"
        "\n"
        "- Opens from city or space - shows level, XP bar, skills,"
        "available points, and chosen traits"
        "\n"
        "- j/k or arrow keys select any of the six skills; TAB switches"
        "between the Stats and Equipment tabs"
        "\n"
        "- ENTER spends a skill point (+1 to that skill)"
        "\n"
        "- Skills at 100 show MAX instead of [+]. ESC closes."
        "\n"
        "- HUD shows a compact XP bar (LV N [#####-----]) so you can"
        "track progress without opening the screen"
        "\n"
        "- When you have unspent skill points, the XP bar turns gold and"
        "shows the count (LV N [#####] +9 PTS) until you spend them (C key)"
        "\n\n"
        "Traits:"
        "\n"
        "- At levels 20 and 30 you choose a trait from the shared pool"
        "\n"
        "- Traits are gated by your playstyle counters - for example,"
        "Ace Pilot requires 10+ combat flees, Juggernaut requires"
        "30+ total kills, Sharpshooter requires 40+ gunnery"
        "\n"
        "- You pick one trait per milestone; the same trait cannot be"
        "chosen twice"
        "\n"
        "- Traits give permanent bonuses: +10% hit chance, +1 AP,"
        "-50% missile damage, or trade price discounts"
        "\n"
        "- Trait effects apply automatically - no activation needed"
        "\n\n"
        "Playstyle counters:"
        "\n"
        "- Tracked automatically: kills, deliveries, bounty completions,"
        "combat flees, weapon shots, damage taken"
        "\n"
        "- Viewable on the Character screen when you reach a milestone"
        "\n"
        "- Counters reset on death (fresh run)"
    ),
)

_GUIDE_NPCS = GuideSection(
    title="NPCs & Factions",
    body=(
        "City guilds:"
        "\n"
        "- Spaceport: buy ships"
        "\n"
        "- Merchant guild: trade contacts and delivery missions"
        "\n"
        "  Found on Earth, Tau Cet b, Mars, Vega b, Epsilon Eri b, Cygni b,"
        "and Indi b"
        "\n"
        "- Militia guild: law enforcement missions"
        "\n"
        "- Bounty guild: bounty hunting missions"
        "\n"
        "- Bar: civilian contacts and rumors"
        "\n\n"
        "NPC interaction:"
        "\n"
        "- Walk into an NPC to open their dialog"
        "\n"
        "- Talk: flavor text and background"
        "\n"
        "- Work: browse available missions"
        "\n"
        "- Deliver: complete a delivery mission for this NPC"
        "\n"
        "- Every faction offers work regardless of reputation - standing "
        "only scales pay"
        "\n\n"
        "Faction reputation (F key):"
        "\n"
        "Your standing with each of the four major factions ranges"
        "from -100 (deeply hated) to +100 (trusted ally). Starting"
        "values depend on your species and class. Press F from"
        "anywhere (city or space) to view current standings with"
        "colored progress bars."
        "\n\n"
        "Five attitude zones:"
        "\n"
        "- Enemy (-100 to -76): hostile on approach (within detect "
        "radius). No trade."
        "\n"
        "- Disliked (-75 to -26): triggers combat on approach "
        "(within detect radius). Lower pay. No trade access."
        "\n"
        "- Neutral (-25 to +25): standard missions, trade, and"
        "dialogue. Default state for most factions."
        "\n"
        "- Liked (+26 to +75): +10% pay, +5% trade prices (sell),"
        "-5% buy prices."
        "\n"
        "- Allied (+76 to +100): +20% pay, +10% sell / -10% buy. "
        "Friendly comms hails."
        "\n\n"
        "How reputation changes:"
        "\n"
        "- Completing missions: delivery missions boost merchant rep;"
        "bounty missions hurt pirate rep; bar missions (pirate-aligned)"
        "hurt merchant/civilian/militia rep."
        "\n"
        "- Combat kills: destroying pirate ships improves militia/"
        "merchant/civilian rep. Attacking lawful factions (merchant,"
        "militia, civilian) damages your standing with everyone."
        "\n"
        "- Fleeing combat: not currently implemented"
        "\n"
        "- Early mission bonus: completing within half the deadline"
        "adds +50% extra rep gain on positive deltas."
        "\n"
        "- Squad bonus: wiping an entire enemy group gives +1 bonus"
        "rep to positive deltas."
        "\n\n"
        "Monthly decay:"
        "\n"
        "Reputation slowly drifts toward neutral over time. Enemy/"
        "Allied zones shift by 3 pts/month, Liked/Disliked by 2 pts."
        "Neutral is stable. Decay stops at -1 or +1 - only your"
        "actions can flip the sign. Check the date in the HUD; months"
        "roll over every 30 game days."
        "\n\n"
        "Trade gating:"
        "\n"
        "- Enemy and Disliked factions refuse to trade with you."
        "- Neutral+: full trade access with reputation-based"
        "discounts (see Trading & Economy)."
        "\n\n"
        "Space mode:"
        "\n"
        "- T opens the comms panel to hail nearby ships"
        "\n"
        "- Hostile ships approaching may trigger combat"
        "\n"
        "- Some systems have NPC traffic (convoys, patrols)"
    ),
)

_GUIDE_DERELICT = GuideSection(
    title="Derelict Ships & Boarding",
    body=(
        "Derelict ships are abandoned wrecks drifting in deep space, far "
        "from planets and trade lanes. They can only be found in frontier "
        "systems (Epsilon Eridani, Procyon, Tau Ceti, Wolf 359, Luyten's "
        "Star, Barnard's Star, and the North Arm: 61 Cygni, Epsilon Indi, "
        "Groombridge 34) and are very rare."
        "\n\n"
        "Finding a derelict:"
        "\n"
        "- When you enter a frontier system, the game rolls a small chance "
        "for a derelict to be present. If one spawns, your sensors pick up "
        "a faint signal."
        "\n"
        "- The derelict appears as an 's' glyph (scout-class wreck) with a "
        "distinct colour. Fly toward it."
        "\n"
        "- Once it enters your viewport, it automatically hails you with "
        "a looping distress beacon. The comms panel shows only 'End "
        "Transmission' - there is no crew to negotiate with."
        "\n\n"
        "Boarding:"
        "\n"
        "- Fly into the derelict and choose 'Board' from the interaction "
        "menu. Your ship cuts through the hull with a breach charge."
        "\n"
        "- The interior is displayed as a tile map of the ship's layout. "
        "Fog of war hides unexplored areas."
        "\n"
        "- Line of sight vs memory: cells in your line of sight render at "
        "full brightness. Cells you've seen before but can no longer see "
        "stay on the map, dimmed - that dim picture is frozen memory, not "
        "live. Creatures and moving objects are only drawn while you have "
        "line of sight to them; step away and they vanish from view, even "
        "though the room stays visible. Static objects (loot piles, "
        "terminals) are remembered and show up dimmed."
        "\n"
        "- Walls (#) block movement and line of sight. Doors (like walls "
        "on the tile map) also block vision but can be stood on once open. "
        "Structural hull walls ({##}) block movement but not vision - they "
        "reveal the ship's silhouette even in fog."
        "\n"
        "- Walk with arrow keys, h/j/k/l, or numpad (diagonals "
        "y/u/b/n). Press P to collect loot on your tile or an adjacent tile. Loot is soft: it never blocks movement or enemy "
        "pathfinding. Exit the way you entered (the breach point marked "
        "with X)."
        "\n\n"
        "Loot:"
        "\n"
        "- Rooms may contain loot piles marked with $ on the floor. Press P "
        "to scavenge loot on your tile or an adjacent tile. Loot "
        "is soft and never blocks movement or enemy pathfinding. Loot is "
        "placed randomly within each room and the total value of the ship "
        "is budgeted at generation time - richer wrecks have more and better "
        "loot."
        "\n\n"
        "Ship computer:"
        "\n"
        "- The cockpit contains a ship computer (C on the map). Bump it to "
        "access the ship's systems. Activating the computer restores "
        "emergency power, increasing your vision range in fog of war so "
        "you can see further into the wreck."
        "\n\n"
        "After exploration:"
        "\n"
        "- When you exit back to space, the derelict is removed from the "
        "system map. Each derelict is a one-time encounter - you cannot "
        "reboard the same wreck."
        "\n"
        "- Only one derelict can be present per system visit. If you leave "
        "the system and return, a new derelict may spawn on a fresh roll."
    ),
)

# All sections in order. Add new sections here (insert or append).
_GUIDE_BAR_MISSIONS = GuideSection(
    title="Bar Missions",
    body=(
        "The Bartender (b glyph, yellow) in the city bar offers shady "
        "pirate-aligned contracts. These are criminal jobs - high pay, "
        "high risk, and they'll damage your reputation with lawful factions."
        "\n\n"
        "Intercept missions:"
        "\n"
        "- Accept from the Bartender, then travel to the target system."
        "\n"
        "- Find the merchant vessel (non-hostile unless you're at enemy rep "
        "with merchants). Hail them via comms (T key) and choose Attack, "
        "or fly close to engage if your merchant rep is hostile."
        "\n"
        "- Destroy the merchant in combat. A salvage container (%) drops "
        "at the wreckage site with the mission-specific good."
        "\n"
        "- Some merchants travel with a pirate fighter escort. Escorts "
        "spawn alongside the merchant and fight as one squad - the "
        "auto-hail and combat trigger work exactly like bounty wingmen. "
        "Hail ANY squad member (merchant or escort) and choose Attack: "
        "the whole group joins the fight. Only destroying the merchant "
        "completes the mission."
        "\n"
        "- Fly over the % to SECURE the stolen cargo. It becomes mission "
        "cargo: reserved in your hold under MISSION CARGO, kept separate "
        "from your trade goods, and cannot be sold. Buying the same good "
        "at a trade terminal does NOT count - only the secured loot does."
        "\n"
        "- Return to the Bartender on the planet where you accepted the "
        "mission and choose Deliver to hand over the goods."
        "\n\n"
        "Smuggling missions:"
        "\n"
        "- Accept a contraband run and the cargo is loaded straight into "
        "your MISSION CARGO hold - it can't be sold, and buying the same "
        "good at a trade terminal won't complete it."
        "\n"
        "- Fly to the destination planet and deliver to the named NPC for "
        "payment. No return trip needed."
        "\n"
        "- Militia cargo scans: when you land on a planet with a militia "
        "building, there's a 40% chance the militia scans your hold. "
        "Contraband found gets confiscated and you pay a fine. Militia "
        "planets telegraph this in gameplay: the planet menu warns you "
        "about the checkpoint on approach, landing while carrying exposed "
        "contraband logs a red warning before the roll, and a triggered "
        "scan announces itself (\"A militia patrol hails you...\") before "
        "the outcome."
        "\n"
        "- The Smuggler's Hold module (see Ships & Equipment) conceals "
        "cargo from scans. Mission smuggling cargo is hidden FIRST, then "
        "any other contraband you carry. If mission cargo overflows the "
        "hold, the mission auto-fails when scanned."
        "\n"
        "- Check the quest log (Q): it shows the contraband type and a "
        "SCAN RISK warning (Low/Medium/High) based on your current hold."
        "\n"
        "- Completing smuggling missions: +2 pirate rep, -5 merchant, "
        "-5 civilian, -8 militia."
        "\n\n"
        "Salvage missions (boarded wreck recovery):"
        "\n"
        "- Accept from the Bartender, then travel to the target system. "
        "Your sensors ping a derelict wreck when you enter the system."
        "\n"
        "- A pirate patrol guards the wreck in space. Clear it (or evade "
        "it) - you can only board while out of combat."
        "\n"
        "- Fly into the wreck and choose Board. The interior is a derelict "
        "layout with scavenger crew inside (see Derelict Ships & Boarding "
        "for interior basics)."
        "\n"
        "- The mission component (a gold % container) is hidden somewhere "
        "in the wreck - the quest log says SOMEWHERE IN THE WRECK until "
        "you find and SECURE it. Search rooms and check the ship computer."
        "\n"
        "- Securing it works like intercept loot: mission cargo, can't be "
        "sold, buying the same good at a terminal doesn't count."
        "\n"
        "- Once secured, exit to space and return to the Bartender to "
        "deliver. The wreck despawns after you leave with the component."
        "\n"
        "- The interior persists between visits: crew you killed stay dead, "
        "loot stays taken, fog stays revealed - no respawn farming."
        "\n"
        "- Completing salvage missions: +3 pirate rep, -3 merchant, "
        "-2 militia."
        "\n\n"
        "Reputation impact:"
        "\n"
        "- Completing intercept missions: +5 pirate rep, -10 merchant, "
        "-5 militia, -2 civilian."
        "\n"
        "- Killing merchants in combat also applies per-kill rep penalties "
        "(see NPCs & Factions)."
        "\n"
        "- The Bartender is aligned with the Pirate faction - your pirate "
        "rep only scales pay; the bar's work is always available."
        "\n\n"
        "Tips:"
        "\n"
        "- Higher-tier merchants are armed and may have escorts."
        "\n"
        "- Early delivery bonus: complete in under half the deadline for "
        "+25-30% extra credits."
        "\n"
        "- Abandoning an intercept mission returns it to the Bartender's board."
    ),
)

_GUIDE_GROUND_GEAR = GuideSection(
    title="Ground Gear & Armory",
    body=(
        "Ground combat (dungeons, derelict ship boarding) uses personal weapons "
        "and armour separate from your ship's loadout. Manage your ground gear "
        "at the Armory Terminal (A symbol on the city map)."
        "\n\n"
        "Armory Terminal:"
        "\n"
        "- Located on every planet with a spaceport, just south of the building"
        "near the mechanic terminal"
        "\n"
        "- Walk into the A glyph to open the buy/sell split-screen"
        "\n"
        "- TAB switches between For Sale (left) and My Loadout (right)"
        "\n"
        "- ENTER on the left panel buys the selected item"
        "\n"
        "- ENTER on the right panel sells the selected item"
        "\n\n"
        "Weapon types:"
        "\n"
        "- Melee (fists, combat knife, stun baton): range 1, infinite ammo, "
        "one- or two-handed"
        "\n"
        "- Pistols (laser, kinetic): range 4, one-handed, limited or "
        "rechargeable ammo"
        "\n"
        "- Rifles (laser, kinetic, shotgun): range 4-7, two-handed, higher damage"
        "\n\n"
        "Weapon slots:"
        "\n"
        "- 2 weapon slots: equip up to two one-handed weapons, or one"
        "two-handed weapon (second slot stays empty with a two-hander)"
        "\n"
        "- Carried weapons not in a slot are kept in your ground inventory"
        "\n\n"
        "Armour slots:"
        "\n"
        "- Head: helmets and headgear"
        "\n"
        "- Body: vests and chest armour (highest defense value)"
        "\n"
        "- Hands: gloves and hand protection"
        "\n"
        "- Legs: leg guards and greaves"
        "\n"
        "- Feet: boots and footwear"
        "\n"
        "Each armour piece provides flat damage reduction per hit."
        "\n\n"
        "Managing gear at the Armory:"
        "\n"
        "- Left panel shows items for sale; ENTER buys and auto-equips"
        "to the first available compatible slot"
        "\n"
        "- Right panel shows your currently equipped loadout (2 weapon"
        "slots + 5 armour slots) with sell prices"
        "\n"
        "- ENTER on a filled slot sells the item for half price, freeing"
        "the slot for a new purchase"
        "\n"
        "- If all compatible slots are full, you must sell before buying"
        "\n\n"
        "Viewing your loadout:"
        "\n"
        "- Press C to open the Character screen, then TAB to switch to"
        "the Equipment tab"
        "\n"
        "- Shows your currently equipped weapon and all armour slots"
    ),
)

_GUIDE_MILITIA_PATROLS = GuideSection(
    title="Militia Patrols & Cargo Scans",
    body=(
        "Militia patrols are law-enforcement ships that monitor space traffic "
        "in most star systems. They appear as teal 'B' glyphs on the space map "
        "and do NOT attack on sight at neutral or better reputation."
        "\n\n"
        "Where they patrol:"
        "\n"
        "- Sol: 3-4 Militia Patrol cruisers (heavy laser + light missile)"
        "\n"
        "- Luyten's Star: 4-5 Militia Enforcer frigates (plasma cannon)"
        "\n"
        "- Alpha Centauri: 2-3 standard patrols"
        "\n"
        "- Sirius, Tau Ceti: 1-2 Militia Scouts (light laser only)"
        "\n"
        "- 61 Cygni: 1-2 Militia Scouts (light laser only)"
        "\n"
        "- Epsilon Indi: 1 Militia Scout (light laser only)"
        "\n"
        "- Frontier systems (Wolf 359, Vega, Barnard's Star, Groombridge 34): none"
        "\n\n"
        "Auto-hail - when you fly within comms range of a militia patrol, "
        "there is a chance they hail you for a cargo scan. Each patrol rolls "
        "independently, exactly once per system visit:"
        "\n"
        "- Allied militia rep: 0% - they wave you through"
        "\n"
        "- Liked: 20% chance"
        "\n"
        "- Neutral: 40% chance"
        "\n"
        "- Disliked or Enemy: 80% chance"
        "\n\n"
        "Interaction options (auto-hail opens comms directly):"
        "\n"
        "- Allow Scan: militia inspects your cargo. Clean = +1 rep. "
        "Contraband found = goods confiscated, fine (50% of value), -5 rep."
        "\n"
        "- Flee: attempt to break line of sight. Flee chance = 40% base "
        "+ (ship speed - 10) x 2% + (piloting - 30) x 0.5%, clamped 15-90%. "
        "Successful = log message, no consequences. Failed = forced combat."
        "\n"
        "- Attack: initiate combat with the patrol. Applies unprovoked attack "
        "rep penalties and pulls the full squad into combat."
        "\n\n"
        "Planet landing scans:"
        "\n"
        "- Landing on a planet with a militia building also triggers a "
        "40% chance cargo scan. The planet menu warns you if you're carrying "
        "contraband before the roll. Same confiscation/fine logic as space."
        "\n\n"
        "Militia Blockade (Luyten's Star):"
        "\n"
        "- The blockade picket line in Luyten's Star is a static formation - "
        "a story element, not a procedural patrol. These ships hail immediately (100% chance) "
        "with a warning to turn back. The only option is End Transmission. "
        "Entering their detect radius triggers combat with the full squad "
        "regardless of reputation."
        "\n\n"
        "Contraband:"
        "\n"
        "- Black Market Weapons (category contraband) are illegal everywhere. "
        "A militia scan will always confiscate them unless hidden by a "
        "Smuggler's Hold module (see Ships & Equipment)."
        "\n"
        "- Smuggling missions (see Bar Missions) are also at risk - mission "
        "cargo with is_smuggle=True counts as contraband for scan purposes."
    ),
)

_GUIDE_GROUND_COMBAT = GuideSection(
    title="Ground Combat",
    body=(
        "Ground combat triggers automatically when a hostile you can see is in "
        "a dungeon - planet surface exploration, derelict ship interiors, or "
        "other boarded locations. "
        "Aggro is your line of sight: a mob joins the fight only when YOU can "
        "see it, within your sight radius (8 tiles - a full room - raised to "
        "20 across the wreck once you restore a derelict's power), and only a "
        "clear ray counts - walls and closed doors block it. No squads, no "
        "shared telepathy: each mob fights as an individual, and mobs that "
        "wander into view mid-fight join the battle (\"joins the fight!\"). "
        "Ambushers lurk near corners - rounding a corner onto one makes it "
        "burst out of hiding and act the same round."
        "The fight ends when nothing hostile is in view - kill them all, or "
        "break sight to disengage. Survivors keep their wounds and revert to "
        "their map behavior, so re-engaging continues the fight at the same "
        "HP, never a heal-on-retrigger. Hunter-type enemies remember where "
        "they last saw you and pursue that cell briefly after disengaging; "
        "guards hold their post and ambushers stay hidden."
        "\n\n"
        "The combat loop is the same turn-based system as space combat, adapted for "
        "personal weapons and armor:"
        "\n\n"
        "Action Points:"
        "\n"
        "- 4 AP per turn for both you and enemies"
        "\n"
        "- Move: 1 AP per cell (arrows, h/j/k/l, or numpad)"
        "\n"
        "- Fire: AP cost varies by weapon (1 AP for fists, 2-4 for guns)"
        "\n"
        "- [w] Wait ends your turn immediately (same as space)"
        "\n"
        "- When AP reaches 0, the enemy takes their turn"
        "\n\n"
        "Hit chance:"
        "\n"
        "chance = weapon_accuracy + (REFLEXES // 2)"
        "\n"
        "       - (target_REFLEXES // 2)"
        "\n"
        "Result clamped to 5%-95%. High REFLEXES improves both your aim and your dodge."
        "\n\n"
        "Damage:"
        "\n"
        "raw = weapon_damage"
        "\n"
        "    + (STRENGTH // 10)  [melee weapons only]"
        "\n"
        "- Armor defense (sum of all 5 equipped armor pieces) is subtracted flat"
        "\n"
        "- Minimum 1 damage per hit"
        "\n"
        "- Your HP = 20 + (STAMINA // 3), e.g. 23 HP at STA 10"
        "\n"
        "- HP persists across multiple fights in the same dungeon visit"
        "\n\n"
        "Weapons:"
        "\n"
        "- Toggle weapons on/off with number keys [1]-[9], same as space combat"
        "\n"
        "- Active weapons show [x] in the HUD; inactive show [ ]"
        "\n"
        "- [f] fires ALL active weapons at the current target"
        "\n"
        "- [Tab] cycles targets (when multiple enemies are present)"
        "\n"
        "- Melee weapons (fists, knives): range 1, infinite ammo"
        "\n"
        "- Ranged weapons (pistols, rifles): longer range than melee; "
        "check the HUD for each weapon's min/max range"
        "\n"
        "- Firing inside a weapon's minimum range is still possible as an "
        "emergency point-blank shot, but costs 35% accuracy per missing "
        "cell and still requires AP and line of sight"
        "\n\n"
        "Armor:"
        "\n"
        "- Up to 5 armor slots: Head, Body, Hands, Legs, Feet"
        "\n"
        "- Each piece adds flat damage reduction (e.g. Heavy Vest +5 DR,"
        "Tactical Gloves +1 DR)"
        "\n"
        "- Armor is passive - no power or toggle management needed"
        "\n"
        "- Buy and equip armor at the Armory terminal (A on city maps)"
        "\n\n"
        "Fleeing:"
        "\n"
        "- [ESC] to attempt to flee: 60% flat chance"
        "\n"
        "- On success: you break contact and return to the dungeon at your current"
        "position. The enemy remains where they were."
        "\n"
        "- On failure: your turn ends (AP set to 0), and the enemy takes their turn."
        "\n\n"
        "Enemy behavior:"
        "\n"
        "- Enemies move toward you when out of weapon range (1 AP per cell)"
        "\n"
        "- Hunters pursue your last-seen position for up to 5 dungeon ticks "
        "after you break line of sight, then resume patrol"
        "\n"
        "- Guards defend their post instead of roaming"
        "\n"
        "- Ambushers hold still until they burst into combat"
        "\n"
        "- They fire their equipped weapon when in range"
        "\n"
        "- Enemy stats (REFLEXES, STRENGTH, STAMINA) affect their combat performance"
        "just like yours"
        "\n"
        "- Tougher enemies (riflemen vs raiders) have better stats, stronger weapons,"
        "and more HP"
        "\n\n"
        "Kills & loot:"
        "\n"
        "- Defeated enemies drop a loot pile (%) at their death position"
        "\n"
        "- Press P while on or next to the loot pile to pick up trade goods "
        "(same as derelict salvage); loot never blocks movement"
        "\n"
        "- Each kill awards XP based on the enemy's difficulty"
        "\n"
        "- Ground combat has no explosion animations - enemies simply collapse"
        "\n\n"
        "Death:"
        "\n"
        "- If your HP reaches 0, your character dies permanently"
        "\n"
        "- A full-screen death frame appears (no HUD, no console log);"
        "any key returns to the main menu and the run is not saved"
        "\n"
        "- You return to the main menu to start a fresh run"
        "\n"
        "- HP does NOT reset between fights in the same dungeon - manage your"
        "health carefully across multiple encounters"
        "\n"
        "- Landing at a city fully heals your HP (cities are safe havens)"
        "\n\n"
        "Ground vs space combat - key differences:"
        "\n"
        "- No shields: armor provides flat DR instead of an absorb layer"
        "\n"
        "- No power pool: ranged weapons track ammo, melee is infinite"
        "\n"
        "- Flat 4 AP per turn (space scales with Piloting)"
        "\n"
        "\n"
        "- No shield regen toggle (armor is always passive)"
        "\n"
        "- REFLEXES/STRENGTH/STAMINA instead of Gunnery/Piloting/Engineering"
        "\n"
        "- Scrolling map view (dungeons can be larger than the screen)"
    ),
)

_GUIDE_MAIN_QUEST = GuideSection(
    title="Main Quest",
    body=(
        "The main quest is a story line that runs alongside the "
        "sandbox. Open the quest log (Q) to see the current step; "
        "nothing about it expires or fails - it waits for you."
        "\n\n"
        "Act 0 - The Door on Mars:"
        "\n"
        "- On your first jump out of Sol, a garbled transmission "
        "arrives through the comms (a full-screen INCOMING "
        "TRANSMISSION overlay). It points to a location on Mars."
        "\n"
        "- Land on Mars and choose 'Explore signal' to search the "
        "surface. The signal site is a hand-built alien landmark "
        "embedded in the procedural caves: follow the connected path "
        "to its lower entrance."
        "\n"
        "- The landmark's C console is the interaction point for the "
        "sealed alien door. It will not open with any human tool."
        "\n"
        "- When the door-opening chain is complete, bump the C console "
        "again. The barrier undulates, parts from the middle, and reveals "
        "a green > marking stairs down. Opening the door completes Act 0; "
        "step onto the marker to begin Act 1's prison descent."
        "\n"
        "- Ask around about the door after using the console: the Barkeep, the Guild Master, "
        "the Militia Captain, and the Research Officers each have a "
        "different way in. Talk to them and pick 'Ask about the "
        "Mars door'."
        "\n"
        "- Accepting a faction's help commits you to that faction's chain; the "
        "other three offers close. The chains are different lengths because "
        "each faction solves the problem in its own way: Militia (6 steps), "
        "Merchants (5), Bar (6), and Lab (7). The door opens only when the "
        "chosen chain is complete."
        "\n\n"
        "Faction chains:"
        "\n"
        "- Each chain mixes the game's mechanics: report to a "
        "faction NPC, descend into a planet's surface caves to "
        "secure a quest cache (delve), recruit an expert on a "
        "distant planet (visit), clear a quest-tagged bounty or "
        "salvage a derelict, and return for the final assembly."
        "\n"
        "- Expert NPCs live on distant planets: the Demolitions "
        "Expert (Epsilon Eridani b), the Salvage Specialist (Tau "
        "Ceti b), the Old Smuggler (Barnard's Star b), and the "
        "Xenolinguist (Alpha Centauri Science Port)."
        "\n"
        "Every chain moves ONE physical object through space, with "
        "escalating danger and a door-opening tool at the end:"
        "\n"
        "- Bar (the Old Smuggler's route): a hot crate of black- "
        "market weapons proves you to the Old Smuggler on Barnard's "
        "Star b. He draws you the cave where the old job went "
        "wrong - recover the rig's power cell, run it to the Wolf "
        "359 listening post for a black-market recharge, then fly "
        "the charged cell back to Earth. While you carry bar-chain "
        "cargo the militia is watching: the cargo-scan chance on "
        "every militia system gets a +30% floor, and with the "
        "charged cell in Sol every patrol actively hunts you. Lose "
        "a crate to a scan and the chain resets - the Barkeep (or "
        "the Old Smuggler) re-issues it. Finish with the brute- "
        "force rig."
        "\n"
        "- Merchants (the Guild Master): dig rare ore from the Wolf "
        "359 caves, smuggle it to the smelter at Tau Ceti b while "
        "consortium ships with pirate escorts hunt you, then fight "
        "through a blockade to recover calibration data from a "
        "derelict near Vega. Finish with the alien-alloy cutter."
        "\n"
        "- Militia (the Captain): recover a scrubbed requisition "
        "from the Mercury caves, run it to the blockade at "
        "Luyten's Star, recruit a demolitions expert, then prove "
        "the breach charge in a live-fire test against five pirate "
        "captains. Finish with the breach charge."
        "\n"
        "- Lab (the Research Officer): chip a sample from the door, "
        "run it to Mercury for analysis, delve Procyon C for a "
        "reference dataset, deliver it to the Xenolinguist, and "
        "board a derelict near Sirius to recover the final "
        "frequency recorder. Finish with the resonance key."
        "\n\n"
        "Time gates:"
        "\n"
        "- Between chain steps the faction works: the next step "
        "unlocks only after a minimum wait on the world clock (a "
        "few in-game months). The quest log reads 'Awaiting word "
        "from the <faction>...' while a gate is pending."
        "\n"
        "- When the wait elapses, the faction sends a one-way comms "
        "message (an INCOMING MESSAGE overlay) naming the next "
        "step's system and planet. Answer it whenever you like - "
        "the step stays available forever."
        "\n"
        "- Delivery steps load their cargo into your mission hold "
        "(a mission appears on the HUD pointing at the target NPC). "
        "Lab, militia, and merchant payloads are plain mission cargo "
        "that scans never touch; only the bar chain's contraband is "
        "at real risk of confiscation."
    ),
)

_GUIDE_DUNGEON_MONSTERS = GuideSection(
    title="Dungeon Monsters",
    body=(
        "Planet surface sites - the Mars signal, Mercury's caves, and other "
        "delve sites - are home to hostile creatures and security drones."
        "\n\n"
        "Unlike pirates and patrols, monsters ignore faction reputation: they "
        "attack on sight no matter your standing, and killing them never "
        "changes how factions view you. They still drop loot and award XP."
        "\n\n"
        "Behaviors:"
        "\n"
        "- Hunters (rock scavengers) patrol the caves and close in when they "
        "spot you. Many hunt in packs."
        "\n"
        "- Guards (sentry drones) hold their position until they spot you, "
        "then open fire at range - they won't chase you far from their post."
        "\n"
        "- Ambushers (ice worms) lie still until you approach, then burst out "
        "in melee. Watch the floor in ice caves."
        "\n\n"
        "Fighting monsters uses the exact same rules as Ground Combat - cover, "
        "line of sight, AP, and armor all work identically. A sentry drone's "
        "laser is not a weapon you can buy: monsters use attacks of their own."
        "\n\n"
        "Some quest caches are guarded: a sentry or assault drone - or, in "
        "Procyon C's caves, a pack of ice worms - holds the room where a "
        "chain's cache is hidden."
        "\n\n"
        "Derelict ships are another matter. Most carry only pirates, but a "
        "rare few are infested: hull parasites lurk in the dark and burst out "
        "when you board. Keep your weapon ready on derelicts."
    ),
)

_GUIDE_TUTORIAL = GuideSection(
    title="Tutorial Mode",
    body=(
        "The Tutorial option on the title menu drops you straight into a "
        "guided first run as a Human Merchant - no character creation."
        "\n\n"
        "It walks you through your first bounty (Crimson Jack), your first "
        "ship loadout, space combat, loot pickup, jumping (which triggers "
        "the main quest), ground combat on Mars, and your first level-up "
        "(spending skill points on the C character screen), using popups "
        "that fire exactly when each moment arrives."
        "\n\n"
        "It is the real game, not a demo: you keep the credits, XP, the "
        "bounty, and the main quest. When the final popup fires, the "
        "tutorial is over and the run continues as a normal sandbox."
        "\n\n"
        "The game autosaves as usual, so ESC and Continue resume your "
        "tutorial run mid-script. Starting a Tutorial (or a New Game) "
        "replaces the previous save."
    ),
)

GUIDE_SECTIONS: tuple[GuideSection, ...] = (
    _GUIDE_TUTORIAL,
    _GUIDE_GAME_OVERVIEW,
    _GUIDE_CONTROLS,
    _GUIDE_DUNGEON_EXTENSIONS,
    _GUIDE_COMBAT,
    _GUIDE_GROUND_COMBAT,
    _GUIDE_DUNGEON_MONSTERS,
    _GUIDE_TRADE,
    _GUIDE_MISSIONS,
    _GUIDE_SHIPS,
    _GUIDE_NAVIGATION,
    _GUIDE_MILITIA_PATROLS,
    _GUIDE_DERELICT,
    _GUIDE_CHARACTER,
    _GUIDE_LEVELING,
    _GUIDE_BAR_MISSIONS,
    _GUIDE_GROUND_GEAR,
    _GUIDE_NPCS,
    _GUIDE_MAIN_QUEST,
)

# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Update
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def _guide_index(topic: str | int | None) -> int | None:
    """Resolve a contextual guide topic by title or section index."""
    if topic is None:
        return None
    if isinstance(topic, int):
        return topic if 0 <= topic < len(GUIDE_SECTIONS) else None
    normalized = topic.strip().casefold()
    return next(
        (index for index, section in enumerate(GUIDE_SECTIONS)
         if section.title.casefold() == normalized),
        None,
    )

def _section_frame(section) -> Any:
    """Build one scrollable guide-section frame.

    ``scrollable`` keeps the fitted font constant for every section
    (long bodies page with PAGE UP/DOWN instead of shrinking the text).
    """
    from . import pygame_screen, pygame_ui

    return pygame_screen.ScreenFrame(
        title=section.title,
        body=tuple(section.body.split("\n")),
        rows=(),
        footer=(pygame_ui.modal_hint(
            "ESC topic list", pygame_ui.GUIDE_HINT,
        ),),
        scrollable=True,
    )


def _run_pygame_help(
    ctx: GameContext,
    initial_topic: str | int | None = None,
) -> bool | None:
    """Run the guide through the shared Pygame screen."""
    from . import pygame_screen, pygame_ui

    list_frame = pygame_screen.ScreenFrame(
        title="SPACEHACK GUIDE",
        body=("Select a topic. Open it with ENTER.",),
        rows=tuple(
            pygame_screen.ScreenRow(
                text=section.title,
                action=f"SECTION:{index}",
            )
            for index, section in enumerate(GUIDE_SECTIONS)
        ),
        footer=(pygame_ui.modal_hint(
            pygame_ui.NAV_HINT, "ENTER open", "ESC close",
        ),),
    )
    initial_index = _guide_index(initial_topic)
    frame = list_frame
    if initial_index is not None:
        frame = _section_frame(GUIDE_SECTIONS[initial_index])
    while True:
        outcome, action, selected = pygame_screen.run_for_context(
            ctx.context, frame, caption="spacehack - guide",
        )
        if outcome == "SELECT" and action.startswith("SECTION:"):
            try:
                index = int(action.split(":", 1)[1])
                section = GUIDE_SECTIONS[index]
            except (ValueError, IndexError):
                return None
            frame = _section_frame(section)
            continue
        if outcome == "TAB":
            frame = list_frame
            continue
        if outcome == "QUIT":
            return True
        if frame is not list_frame:
            frame = list_frame
            continue
        if outcome == "BACK":
            return True
        if outcome == "PAGE_UP" or outcome == "PAGE_DOWN":
            continue

def _run_help_guide(ctx: GameContext) -> None:
    """Open the game guide as a modal, optionally at a contextual topic."""
    topic = getattr(ctx, "_guide_topic", None)
    if hasattr(ctx, "_guide_topic"):
        delattr(ctx, "_guide_topic")
    result = _run_pygame_help(ctx, topic)
    if result is None:
        raise RuntimeError("Guide returned no outcome")
    return

def _open_context_guide(ctx: GameContext, topic: str) -> None:
    """Open the guide directly at the topic most relevant to a modal."""
    ctx._guide_topic = topic
    _run_help_guide(ctx)
